score = int(input("enter your score :   "))
if score > 100 : print("กรุณาใส่คะแนนระหว่าง 0 - 100 เท่านั้น")
elif score > 79 : print("A")
elif score > 74 : print("B+")
elif score > 69 : print("B")
elif score > 64 : print("C+")
elif score > 59 : print("C")
elif score > 54 : print("D+")
elif score > 49 : print("D")
elif score >= 0 : print("F")
else: print("กรุณาใส่คะแนนระหว่าง 0 - 100 เท่านั้น")
# solution two 
new_score = int(input("Enter your score  :  "))
if new_score > 100 : print("Error")
elif new_score > 79 : print("A")
elif new_score > 69 : print("B")
elif new_score > 59 : print("C")
elif new_score > 49 : print("D")
elif new_score >= 50 : print("F")
else : print("Error")